# Generated by Django 6.0.5 on 2026-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], max_length=50),
        ),
    ]
