# Generated by Django 6.0.5 on 2026-07-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_project_team_links(apps, schema_editor):
    """
    For every existing Project with the old `team` FK set, create an
    equivalent ProjectTeam link so team access isn't silently lost when the
    old field is removed in the next migration. CONTRIBUTOR is the same
    default new explicit members get (ProjectSettings.default_member_role) -
    a reasonable default since team assignment previously granted no access
    at all, so any role here is a pure addition, not a behavior regression.
    """
    Project = apps.get_model('projects', 'Project')
    ProjectTeam = apps.get_model('projects', 'ProjectTeam')

    for project in Project.objects.exclude(team__isnull=True):
        ProjectTeam.objects.create(
            project=project,
            team_id=project.team_id,
            role="CONTRIBUTOR",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmembership_role'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], max_length=50)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='projects.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='teams.team')),
            ],
            options={
                'indexes': [models.Index(fields=['project'], name='projects_pr_project_a61654_idx'), models.Index(fields=['team'], name='projects_pr_team_id_4fa4ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('project',), name='unique_project_team_link')],
            },
        ),
        migrations.RunPython(backfill_project_team_links, reverse_code=migrations.RunPython.noop),
    ]
