# Generated by Django 6.0.5 on 2026-07-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_team_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
