# Generated by Django 6.0.5 on 2026-07-19 04:55

from django.conf import settings
from django.db import migrations, models


def backfill_is_owning(apps, schema_editor):
    """
    The old constraint guaranteed at most one ProjectTeam row per project, so
    every existing row unambiguously becomes that project's owning team.
    """
    ProjectTeam = apps.get_model('projects', 'ProjectTeam')
    ProjectTeam.objects.update(is_owning=True)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_team_fk'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='is_owning',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_is_owning, reverse_code=migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='projectteam',
            name='unique_project_team_link',
        ),
        migrations.AddConstraint(
            model_name='projectteam',
            constraint=models.UniqueConstraint(fields=('project', 'team'), name='unique_project_team_pair'),
        ),
        migrations.AddConstraint(
            model_name='projectteam',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owning', True)), fields=('project',), name='unique_owning_team_per_project'),
        ),
    ]
