# Generated by Django 6.0.5 on 2026-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='create_task_min_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='MANAGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='default_member_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='CONTRIBUTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='delete_task_min_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='MANAGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='invite_member_min_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='MANAGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='remove_member_min_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='MANAGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='update_member_min_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='MANAGER', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='update_task_min_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer'), ('GUEST', 'Guest')], default='MANAGER', max_length=20),
        ),
    ]
